services:
  backend:
    image: ghcr.io/7azem512/fitlink-backend:latest
    container_name: fitlink-backend

    ports:
      - "8080:8080"

    env_file:
      - .env

    restart: unless-stopped

    volumes:
      - uploads:/app/uploads

    networks:
      - fitlink-network

volumes:
  uploads:

networks:
  fitlink-network:
    driver: bridge
