spring.application.name=FitLink
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/fitlink}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:12345}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# JWT Configuration
application.jwt.secret=${JWT_SECRET:N13XoKAgf1F5eAJDubtcbINOvSGxSOwMRcsKhX1sbgw=}

# Mail Configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:azmex.app@gmail.com}
spring.mail.password=${MAIL_PASSWORD:bovzgzfogqvtubyn}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

server.forward-headers-strategy=framework

# Logging Configuration
logging.level.root=WARN
logging.level.com.project.FitLink=INFO
logging.level.org.springframework.security=DEBUG